// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/protobuf/user/api.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	api/protobuf/user/api.proto
	api/protobuf/user/user.proto

It has these top-level messages:
	LoginRequest
	User
	ID
	Phone
	Email
	Nickname
	Account
	IDPassword
	IDPhone
	IDEmail
	IDNickname
	IDAvatar
	IDStatus
*/
package user

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *LoginRequest) Validate() error {
	return nil
}
